version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'postgres'
  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f ./backend/tmp/pids/server.pid && bundle exec rails s -p 8000 -b '0.0.0.0'"
    image: rails:dev
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/Book-rese
      - ./backend/vendor/bundle:/Book-rese/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - "./app/redis:/data"
  # frontend:
  #   build: 
  #     context: ./frontend/
  #     dockerfile: Dockerfile
  #   tty: true
  #   volumes:
  #     - ./frontend:/app
  #   command: sh -c "yarn start"
  #   ports:
  #     - 3000:3000
volumes:
  postgres-data:
    driver: local