version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports: 
      - 5432:5432
  backend:
    build: 
      context: ./
      dockerfile: Dockerfile.development
    command: /bin/sh -c "rm -f ./tmp/pids/server.pid && bundle exec rails s -p 8000 -b '0.0.0.0'"
    image: rails-book-rese:dev
    stdin_open: true
    tty: true
    volumes:
      - ./:/Book-rese-backend
      - ./vendor/bundle:/Book-rese-backend/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - "./app/redis:/data"
volumes:
  postgres-data:
    driver: local