version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports: 
      - 5432:5432
  backend:
    build: 
      context: ./
      dockerfile: Dockerfile.development
    # command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    image: rails-dev
    stdin_open: true
    tty: true
    volumes:
      - ./:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
  web-server:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    image: nginx:dev
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 8000:80
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - "./app/redis:/data"
volumes:
  postgres-data:
    driver: local

  public-data:
  tmp-data:
  log-data: