export {default as BodyCard} from './BodyCard'
export {default as Header} from './Header'
export {default as Content} from './Content'
export {default as About} from './About'
export {default as PostContent} from './PostContent'